stages:
  - validate

validate-job:
  stage: validate
  image: registry.gitlab.com/4s1/docker/node:14-alpine-dev
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
  before_script:
    # Access to private packages
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test
