stages:
  - validate

validate-job:
  stage: validate
  image: registry.gitlab.com/4s1/docker/node:14-alpine-dev
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
  script:
    - pnpm i
    - pnpm run lint
    - pnpm run build
    - pnpm run test
